# 1.1 Numpy

## 1.1.1 Array

In [1]:
import numpy as np

In [2]:
x = np.array([i for i in range(10)])
print(x.__class__)
print(x.shape)
print(x.ndim)

<class 'numpy.ndarray'>
(10,)
1


In [3]:
W = np.array([[i for i in range(10)], [i for i in range(10)]])
print(W.shape)
print(W.ndim)

(2, 10)
2


## 1.1.2 Element Wise

In [4]:
W = np.array([[0, 0, 0], [1, 1, 1]])
X = np.array([[1, 2, 3], [4, 5, 6]])
print(W + X)
print(W - X)
print(W * X)
print(W / X)
print(W // X)
print(X / W)

[[1 2 3]
 [5 6 7]]
[[-1 -2 -3]
 [-3 -4 -5]]
[[0 0 0]
 [4 5 6]]
[[0.         0.         0.        ]
 [0.25       0.2        0.16666667]]
[[0 0 0]
 [0 0 0]]
[[inf inf inf]
 [ 4.  5.  6.]]


/Users/wuling31715/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


## 1.1.3 Broadcast

In [5]:
A = np.array([[0, 1], [2, 3]])
print(A + 10)
print(A * 10)

[[10 11]
 [12 13]]
[[ 0 10]
 [20 30]]


In [6]:
b = np.array([10, 20])
print(A + b)
print(A * b)

[[10 21]
 [12 23]]
[[ 0 20]
 [20 60]]


## 1.1.4 Dot

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

32


In [8]:
b = np.array([[4], [5], [6]])
print(np.dot(a, b))

[32]


In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 0], [0, 1]])
print(np.dot(A, B))

[[1 2]
 [3 4]]


## 1.1.5 Shape

In [10]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
c = a * b # Broadcast
print(c)
print(c.shape)

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
(3, 3)


In [11]:
d = np.dot(a, b) # Dot
print(d)
print(d.shape)

[32]
(1,)


# 1.2 Theory of Neural Network

## 1.2.1 Concept of Neural Network

In [12]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [13]:
x = np.random.randn(10, 2) # 輸入
W1 = np.random.randn(2, 4) # 權重
b1 = np.random.randn(4) # 偏權值 
h = np.dot(x, W1) + b1
W2 = np.random.randn(4, 3) # 權重
b2 = np.random.randn(3) # 偏權值 
a = sigmoid(h)
s = np.dot(a, W2) + b2
print('x:\n{}\n'.format(x))
print('W1:\n{}\n'.format(W1))
print('b1:\n{}\n'.format(b1))
print('h:\n{}\n'.format(h))
print('a:\n{}\n'.format(a))
print('W2:\n{}\n'.format(W2))
print('b2:\n{}\n'.format(b2))
print('s:\n{}\n'.format(s))

x:
[[-0.10902493 -1.18328913]
 [ 0.53702433 -0.39854397]
 [-0.48360479 -2.68484645]
 [-0.21476524  0.89463263]
 [ 0.50923127  0.25887298]
 [-0.37989214  0.27841572]
 [-0.43938412 -0.24956396]
 [-0.41270945 -0.71083544]
 [ 0.32391035 -0.37285778]
 [-1.5052909   1.0003075 ]]

W1:
[[-0.63373603 -0.08766833 -1.30378141 -0.00965526]
 [-0.836911    0.60756915  0.63021141 -0.67363184]]

b1:
[-0.20526216  1.42704184 -1.22486174  0.07637015]

h:
[[ 0.85413856  0.71766991 -1.82843938  0.87452405]
 [-0.21204799  1.13781879 -2.17619103  0.33965695]
 [ 2.34819315 -0.1617912  -2.28636768  1.88963754]
 [-0.81788557  1.98942114 -0.38104712 -0.52420926]
 [-0.74463401  1.53968162 -1.72564329 -0.10293169]
 [-0.19752     1.62950315 -0.55410467 -0.10751158]
 [ 0.28205421  1.31393455 -0.80927895  0.24872675]
 [ 0.65119269  1.03134171 -1.13475544  0.55919636]
 [-0.09848704  1.17210828 -1.88214927  0.32441159]
 [-0.08847342  2.16676416  1.36811375 -0.58293485]]

a:
[[0.70143458 0.67209371 0.13842429 0.7056861

## 1.2.2 Forward Propagation

In [14]:
class Sigmoid:
    def __init__(self):
        self.params = list()
        
    def forward(self, x):
        return 1 / (1+np.exp(-x))

In [15]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [16]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        # 初始化權重、偏移值
        I, H, O = input_size, hidden_size, output_size        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        # 連接各層神經網路
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        # 儲存參數
        self.params = list()
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [17]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print('x:\n{}\n'.format(x))
print('s:\n{}\n'.format(s))

x:
[[ 0.18122376  1.50968581]
 [ 0.05897737  2.27987997]
 [-1.08906151 -0.70449369]
 [ 0.05485299  0.1109819 ]
 [-1.70110958 -1.05196525]
 [ 1.55405622  0.64690704]
 [-0.8667716  -0.3068677 ]
 [-1.20848185 -2.01184419]
 [-0.15153892 -0.34816285]
 [-0.38557372 -0.87434894]]

s:
[[ 1.07169617 -1.195476   -0.18140381]
 [ 0.81216049 -1.2471672  -0.20852234]
 [ 1.89870039 -0.7651228  -0.60428021]
 [ 1.53818275 -1.03208853 -0.2020218 ]
 [ 2.01677109 -0.67002042 -0.77866112]
 [ 1.24071943 -1.18900127  0.2000497 ]
 [ 1.78373297 -0.8442492  -0.54106641]
 [ 2.11255762 -0.59860074 -0.55126119]
 [ 1.68642184 -0.94712887 -0.26522424]
 [ 1.83719293 -0.84329367 -0.33464905]]

