# 1.2.1 Concept of Neural Network

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [3]:
x = np.random.randn(10, 2) # 輸入
W1 = np.random.randn(2, 4) # 權重
b1 = np.random.randn(4) # 偏權值 
h = np.dot(x, W1) + b1
W2 = np.random.randn(4, 3) # 權重
b2 = np.random.randn(3) # 偏權值 
a = sigmoid(h)
s = np.dot(a, W2) + b2
print('x:\n{}\n'.format(x))
print('W1:\n{}\n'.format(W1))
print('b1:\n{}\n'.format(b1))
print('h:\n{}\n'.format(h))
print('a:\n{}\n'.format(a))
print('W2:\n{}\n'.format(W2))
print('b2:\n{}\n'.format(b2))
print('s:\n{}\n'.format(s))

x:
[[ 1.39364169  0.34525633]
 [ 0.08647562  0.41996989]
 [-0.23371686  0.48018946]
 [ 0.40490286  0.45149075]
 [ 0.51052378  1.10963402]
 [ 1.23912935  2.81313832]
 [ 0.46670756 -0.03635947]
 [-1.70524022 -1.31237287]
 [-0.54322253 -0.0386003 ]
 [ 1.35693     1.03510733]]

W1:
[[ 0.61740979 -0.31067968  1.21997204  0.57661626]
 [ 0.58411242  1.33650497 -0.42758114 -0.24510911]]

b1:
[ 1.32884912 -1.19555098 -1.06531337  0.91713032]

h:
[[ 2.39096566 -1.16709033  0.48726543  1.6361013 ]
 [ 1.62754964 -0.66112535 -1.13938674  0.86405512]
 [ 1.46503466 -0.48116429 -1.55576136  0.66466656]
 [ 1.84256146 -0.71792643 -0.76439213  1.03993939]
 [ 2.2922025   0.12887104 -0.91694721  0.93952522]
 [ 3.73708874  2.17925006 -0.7564551   0.9421066 ]
 [ 1.59576092 -1.38914215 -0.48039657  1.19515352]
 [-0.49055618 -2.41976034 -2.58451287  0.25553564]
 [ 0.97091129 -1.07837227 -1.7115249   0.61336067]
 [ 2.77125003 -0.23369547  0.14751092  1.44584397]]

a:
[[0.91613579 0.23738132 0.61946203 0.8370037

# 1.2.2 Forward Propagation

In [4]:
import numpy as np

In [5]:
class Sigmoid:
    def __init__(self):
        self.params = list()
        
    def forward(self, x):
        return 1 / (1+np.exp(-x))

In [6]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [7]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        # 初始化權重、偏移值
        I, H, O = input_size, hidden_size, output_size        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        # 連接各層神經網路
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        # 儲存參數
        self.params = list()
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [8]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print('x:\n{}\n'.format(x))
print('s:\n{}\n'.format(s))

x:
[[-0.62996816  0.67593066]
 [-0.45762297 -0.61162736]
 [ 0.72714269  0.80743892]
 [-1.34137246 -0.15494094]
 [-0.24104293  1.08510406]
 [-0.70534539 -0.41611903]
 [-1.29889352 -0.54765425]
 [ 2.81424675 -0.1745559 ]
 [ 0.18109439  0.39781567]
 [-0.19541212 -2.44379933]]

s:
[[ 0.30941915 -0.50620898 -0.51082974]
 [-0.29988855 -0.76299582 -0.98833604]
 [ 0.38909195 -0.48225835 -0.4205968 ]
 [-0.19030743 -0.72278351 -0.85958942]
 [ 0.53432735 -0.43878937 -0.38565153]
 [-0.24346898 -0.7420752  -0.93238929]
 [-0.37770097 -0.78040587 -0.96217517]
 [-0.09267602 -0.60172521 -0.55896688]
 [ 0.18076184 -0.53863275 -0.55236336]
 [-0.79251242 -0.79609131 -1.14802663]]

