# 1.2.1 Concept of Neural Network

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [3]:
x = np.random.randn(10, 2) # 輸入
W1 = np.random.randn(2, 4) # 權重
b1 = np.random.randn(4) # 偏權值 
h = np.dot(x, W1) + b1
W2 = np.random.randn(4, 3) # 權重
b2 = np.random.randn(3) # 偏權值 
a = sigmoid(h)
s = np.dot(a, W2) + b2
print('x:\n{}'.format(x))
print('W1:\n{}\n'.format(W1))
print('b1:\n{}\n'.format(b1))
print('h:\n{}\n'.format(h))
print('a:\n{}\n'.format(a))
print('W2:\n{}\n'.format(W2))
print('b2:\n{}\n'.format(b2))
print('s:\n{}\n'.format(s))

x:
[[ 1.54056804 -1.61526592]
 [ 0.64961739  0.77813595]
 [-1.05933942 -0.39374068]
 [ 0.37451013  0.4404055 ]
 [ 0.38544104  0.37420456]
 [ 1.80659898 -0.24144267]
 [ 1.0232331   1.88849452]
 [-0.42121708  1.96782407]
 [-0.54842548 -0.4899663 ]
 [ 0.51043321  1.21374963]]
W1:
[[-0.07371476 -1.17501217 -1.11046383  1.71681991]
 [-0.29953074  0.21189501 -0.81575034  2.13153472]]

b1:
[ 1.97150026  1.09380716 -1.19808039  0.39986931]

h:
[[ 2.34175944 -1.05864583 -1.59117175 -0.39824819]
 [ 1.69053824  0.49538195 -2.55422166  3.17376916]
 [ 2.16752665  2.2551122   0.29947182 -2.25809762]
 [ 1.81197835  0.74707294 -1.97322127  1.98157537]
 [ 1.8310018   0.72020133 -1.93135621  1.85923217]
 [ 1.91064674 -1.08012913 -3.00728627  2.98683098]
 [ 1.33041072  0.29165838 -3.87488378  6.1819679 ]
 [ 1.41312639  2.00571446 -2.33558721  3.87120077]
 [ 2.15868728  1.63439237 -0.18938356 -1.58605864]
 [ 1.57031848  0.75122943 -2.75501468  3.86334068]]

a:
[[0.91227699 0.25756832 0.1692191  0.4017333 

# 1.2.2 Forward Propagation

In [4]:
import numpy as np

In [5]:
class Sigmoid:
    def __init__(self):
        self.params = list()
        
    def forward(self, x):
        return 1 / (1+np.exp(-x))

In [6]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [7]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        # 初始化權重、偏移值
        I, H, O = input_size, hidden_size, output_size        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        # 連接各層神經網路
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        # 儲存參數
        self.params = list()
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [8]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print('x:\n{}\n'.format(x))
print('s:\n{}\n'.format(s))

x:
[[-0.23152811  1.53243252]
 [ 0.08968794 -1.55956123]
 [ 2.57285184  1.0186436 ]
 [-2.29532958 -0.66375209]
 [ 0.94152432 -0.94010522]
 [-0.45401835  0.62810133]
 [-1.0098573  -1.01911098]
 [ 2.52251939 -0.92706371]
 [ 1.01871112  0.06691501]
 [-1.836088    0.43912979]]

s:
[[ 2.74386282 -1.31683564  0.44586362]
 [ 2.01489165 -2.35522538  1.18756454]
 [ 3.6168653  -0.43195754  0.5515123 ]
 [ 1.48928315 -2.78157599  1.92169045]
 [ 2.82725247 -1.42015509  0.63438762]
 [ 2.30374905 -1.79898521  0.65052509]
 [ 1.64191885 -2.63295173  1.651295  ]
 [ 3.49400008 -0.68949697  0.64735195]
 [ 3.15358324 -0.97443438  0.5213762 ]
 [ 1.64135877 -2.42686218  1.44977459]]

