# 1.1.1 Array

In [1]:
import numpy as np

In [2]:
x = np.array([i for i in range(10)])

In [3]:
x.__class__

numpy.ndarray

In [4]:
x.shape

(10,)

In [5]:
x.ndim

1

In [6]:
W = np.array([[i for i in range(10)], [i for i in range(10)]])

In [7]:
W.shape

(2, 10)

In [8]:
W.ndim

2

# 1.1.2 Element Wise

In [9]:
W = np.array([[0, 0, 0], [1, 1, 1]])

In [10]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
W + X

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
W - X

array([[-1, -2, -3],
       [-3, -4, -5]])

In [13]:
W * X

array([[0, 0, 0],
       [4, 5, 6]])

In [14]:
W / X

array([[0.        , 0.        , 0.        ],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
W // X

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
X / W

/Users/wuling31715/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [ 4.,  5.,  6.]])

# 1.1.3 Broadcast

In [17]:
A = np.array([[0, 1], [2, 3]])

In [18]:
A + 10

array([[10, 11],
       [12, 13]])

In [19]:
A * 10

array([[ 0, 10],
       [20, 30]])

In [20]:
b = np.array([10, 20])

In [21]:
A + b

array([[10, 21],
       [12, 23]])

In [22]:
A * b

array([[ 0, 20],
       [20, 60]])

# 1.1.4 Dot

In [23]:
a = np.array([1, 2, 3])

In [24]:
b = np.array([4, 5, 6])

In [25]:
np.dot(a, b)

32

In [26]:
b = np.array([[4], [5], [6]])

In [27]:
np.dot(a, b)

array([32])

In [28]:
A = np.array([[1, 2], [3, 4]])

In [29]:
B = np.array([[1, 0], [0, 1]])

In [30]:
np.dot(A, B)

array([[1, 2],
       [3, 4]])

# 1.1.5 Shape

In [31]:
a = np.array([1, 2, 3])

In [32]:
b = np.array([[4], [5], [6]])

In [33]:
c = a * b # Broadcast

In [34]:
c

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [35]:
c.shape

(3, 3)

In [36]:
d = np.dot(a, b) # Dot

In [37]:
d

array([32])

In [38]:
d.shape

(1,)