# 1.1.1 Array

In [1]:
import numpy as np

In [2]:
x = np.array([i for i in range(10)])

In [3]:
x.__class__

numpy.ndarray

In [4]:
x.shape

(10,)

In [5]:
x.ndim

1

In [6]:
W = np.array([[i for i in range(10)], [i for i in range(10)]])

In [7]:
W.shape

(2, 10)

In [8]:
W.ndim

2

# 1.1.2 Element Wise

In [9]:
W = np.array([[0, 0, 0], [1, 1, 1]])

In [10]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
W + X

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
W - X

array([[-1, -2, -3],
       [-3, -4, -5]])

In [13]:
W * X

array([[0, 0, 0],
       [4, 5, 6]])

In [14]:
W / X

array([[0.        , 0.        , 0.        ],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
W // X

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
X / W

/Users/wuling31715/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [ 4.,  5.,  6.]])